Repository SELab-2/OSOC-5, pull requests merged in 2022-04, with the labels that each got.

#247 Be/api fixes
  be/README.md
  be/osoc/common/migrations/0001_initial.py
  be/osoc/common/migrations/0002_alter_student_gender.py
  be/osoc/common/migrations/0003_auto_20220419_1218.py
  be/osoc/common/migrations/0004_merge_20220420_1557.py
  be/osoc/common/models.py
  be/osoc/common/serializers.py
  be/osoc/common/tests/tests.py
  be/osoc/common/views.py
Labels: enhancement, backend

#114 Tally integration.
  .github/workflows/django.yml
  be/osoc/common/fixtures/fixtures.json
  be/osoc/common/migrations/0001_initial.py
  be/osoc/common/migrations/0002_alter_student_gender.py
  be/osoc/common/migrations/0003_auto_20220419_1218.py
  be/osoc/common/migrations/0004_merge_20220420_1557.py
  be/osoc/common/tally/questions.json
  be/osoc/common/tally/tally.py
  be/osoc/common/tests/tests.py
  be/osoc/common/utils.py
  be/osoc/common/views.py
Labels: backend

#268 Fe/select students improvement
  fe/src/features/students/components/LanguageCard.vue
Labels: enhancement, frontend

#272 possible fix for server
  be/osoc/settings/common.py
  fe/src/stores/useAuthenticationStore.ts
Labels: bug, frontend

#270 Refactor
  be/osoc/common/fixtures/fixtures.json
  be/osoc/common/migrations/0001_initial.py
  be/osoc/common/models.py
  be/osoc/common/serializers.py
  be/osoc/common/tests/tests.py
  be/osoc/common/views.py
  fe/src/components/StudentCard.vue
  fe/src/features/projects/CreateProject.vue
  fe/src/features/projects/components/BasicInfo.vue
  fe/src/features/projects/components/ProjectCoaches.vue
  fe/src/features/projects/components/ProjectRoles.vue
  fe/src/features/projects/components/subcomponents/CoachTable.vue
  fe/src/features/projects/components/subcomponents/DeleteRoleDialog.vue
  fe/src/features/projects/components/subcomponents/NewRoleDialog.vue
  fe/src/features/projects/components/subcomponents/RoleTable.vue
  fe/src/features/students/StudentPage.vue
  fe/src/features/students/components/SuggestionsCard.vue
  fe/src/models/Project.ts
  fe/src/models/ProjectCoachColumns.ts
  fe/src/models/ProjectRolesColumns.ts
  fe/src/models/Student.ts
  fe/src/models/Suggestion.ts
  fe/src/stores/useCoachStore.ts
  fe/src/stores/useProjectStore.ts
  fe/src/stores/useSkillStore.ts
  fe/src/stores/useStudentStore.ts
Labels: enhancement, frontend

#267 Small improvements and cleanup
  fe/src/components/TopToolbar.vue
  fe/src/features/authentication/FormPage.vue
  fe/src/features/authentication/LoginForm.vue
  fe/src/features/authentication/SignupForm.vue
  fe/src/features/projects/ProjectList.vue
  fe/src/router/index.ts
Labels: enhancement, frontend

#266 Front end tests
  README.md
  fe/package-lock.json
  fe/src/stores/useSkillStore.ts
  fe/tests/components/gitHubSignInButton.test.ts
  fe/tests/components/loadingSpinner.test.ts
  fe/tests/components/notFoundPage.test.ts
  fe/tests/stores/skillStore.test.ts
Labels: frontend, tests
