Repository SELab-2/OSOC-5, pull requests merged in 2022-05, with the labels that each got.

#296 add docstrings and fix pylint errors
  be/osoc/common/adapters.py
  be/osoc/common/admin.py
  be/osoc/common/apps.py
  be/osoc/common/consumers.py
  be/osoc/common/filters.py
  be/osoc/common/forms.py
  be/osoc/common/models.py
  be/osoc/common/routing.py
  be/osoc/common/serializers.py
  be/osoc/common/signals.py
  be/osoc/common/tally/tally.py
  be/osoc/common/tests/__init__.py
  be/osoc/common/tests/integration_tests.py
  be/osoc/common/tests/test_filters.py
  be/osoc/common/tests/test_models.py
  be/osoc/common/tests/test_tallyform.py
  be/osoc/common/tests/test_utils.py
  be/osoc/common/utils.py
  be/osoc/common/views.py
  be/osoc/settings/dev.py
  be/osoc/settings/prod.py
  be/requirements.txt
Labels: backend

#301 Backend pagination.
  be/osoc/common/pagination.py
  be/osoc/common/tests/integration_tests.py
  be/osoc/common/tests/test_filters.py
  be/osoc/common/views.py
  be/osoc/settings/common.py
Labels: backend

#312 Disable broken fe-test
  fe/tests/components/gitHubSignInButton.disabledtest.ts
Labels: bug, frontend, tests

#327 Coachview restrictions
  fe/src/App.vue
  fe/src/components/TopToolbar.vue
  fe/src/features/mails/MailList.vue
  fe/src/features/projects/CreateProject.vue
  fe/src/features/projects/ProjectList.vue
  fe/src/features/users/UserList.vue
  fe/src/models/Project.ts
  fe/src/models/ProjectSuggestion.ts
  fe/src/models/Student.ts
  fe/src/models/User.ts
  fe/src/router/index.ts
  fe/src/stores/useCoachStore.ts
  fe/src/stores/useProjectStore.ts
  fe/src/stores/useStudentStore.ts
Labels: enhancement, frontend

#336 Updated checkboxes in sidebar
  fe/src/components/SideBar.vue
Labels: frontend

#330 Temporarily show new suggestions
  fe/src/features/mails/components/MailsOverview.vue
  fe/src/features/projects/ProjectList.vue
  fe/src/features/projects/components/ProjectCard.vue
  fe/src/features/projects/components/ProjectCardSuggestion.vue
  fe/src/features/students/components/InfoDiv.vue
  fe/src/models/ProjectSuggestion.ts
  fe/src/stores/useProjectStore.ts
  fe/src/stores/useSkillStore.ts
Labels: enhancement, frontend

#338 filtered final_decisions out of suggestions
  be/osoc/common/serializers.py
  be/osoc/common/views.py
Labels: enhancement, backend

#333 add resolve conflicts api endpoint
  be/osoc/common/serializers.py
  be/osoc/common/views.py
Labels: enhancement, backend

#339 Fe/comments lisa
  be/osoc/common/pagination.py
  be/osoc/common/tests/integration_tests.py
  be/osoc/common/tests/test_filters.py
  be/osoc/common/views.py
  be/osoc/settings/common.py
  fe/src/App.vue
  fe/src/components/DecisionIcon.vue
  fe/src/components/SegmentedControl.vue
  fe/src/components/SideBar.vue
  fe/src/components/StudentCard.vue
  fe/src/components/TopToolbar.vue
  fe/src/features/mails/MailList.vue
  fe/src/features/mails/components/MailsOverview.vue
  fe/src/features/projects/CreateProject.vue
  fe/src/features/projects/ProjectList.vue
  fe/src/features/projects/components/BasicInfo.vue
  fe/src/features/projects/components/ProjectCard.vue
  fe/src/features/projects/components/ProjectSkills.vue
  fe/src/features/projects/components/subcomponents/DeleteSkillDialog.vue
  fe/src/features/projects/components/subcomponents/NewRoleDialog.vue
  fe/src/features/projects/components/subcomponents/NewSkillDialog.vue
  fe/src/features/projects/components/subcomponents/SkillTable.vue
  fe/src/features/students/SelectStudentsPage.vue
  fe/src/features/students/StudentPage.vue
  fe/src/features/students/components/InfoDiv.vue
  fe/src/features/students/components/SuggestionsCard.vue
  fe/src/features/users/UserList.vue
  fe/src/models/GenderOptions.ts
  fe/src/models/Project.ts
  fe/src/models/ProjectRolesColumns.ts
  fe/src/models/ProjectSkillsColumns.ts
  fe/src/models/ProjectSuggestion.ts
  fe/src/models/QuasarColors.ts
  fe/src/models/RolesOptions.ts
  fe/src/models/Student.ts
  fe/src/models/User.ts
  fe/src/models/YesMaybeNoOptions.ts
  fe/src/router/index.ts
  fe/src/stores/useCoachStore.ts
  fe/src/stores/useMailStore.ts
  fe/src/stores/useProjectStore.ts
  fe/src/stores/useSkillStore.ts
  fe/src/stores/useStudentStore.ts
  fe/tests/components/gitHubSignInButton.disabledtest.ts
  fe/tests/components/gitHubSignInButton.test.ts
Labels: documentation, frontend

#343 Project List Filtering & Comments improvements
  fe/src/features/projects/ProjectList.vue
  fe/src/features/projects/components/ProjectCard.vue
  fe/src/features/projects/components/ProjectCardSuggestion.vue
  fe/src/stores/useProjectStore.ts
Labels: enhancement, frontend

#318 Improve Github actions
  .github/workflows/django.yml
  .github/workflows/pylint.yml
  .github/workflows/vue.yml
  be/manage.py
  be/osoc/settings/common.py
Labels: bug, enhancement

#350 be: hotfix integration test.
  be/osoc/common/tests/integration_tests.py
Labels: bug, backend, tests

#346 Fix for scrolling issues on student page
  fe/src/features/students/StudentPage.vue
Labels: bug, frontend

#345 Sidebar bugs
  fe/src/components/SideBar.vue
  fe/src/stores/useStudentStore.ts
Labels: bug, frontend

#329 added ordering
  be/osoc/common/views.py
Labels: enhancement, backend

#347 Frontend bug fixes
  fe/src/features/users/AddUser.vue
  fe/src/features/users/UserList.vue
Labels: bug, frontend

#332 edit/delete project
  fe/src/features/projects/CreateProject.vue
  fe/src/features/projects/EditProject.vue
  fe/src/features/projects/components/BasicInfo.vue
  fe/src/features/projects/components/ProjectCard.vue
  fe/src/features/projects/components/ProjectCoaches.vue
  fe/src/features/projects/components/ProjectSkills.vue
  fe/src/features/projects/components/subcomponents/DeleteProjectDialog.vue
  fe/src/features/projects/components/subcomponents/DeleteSkillDialog.vue
  fe/src/features/projects/components/subcomponents/NewSkillDialog.vue
  fe/src/features/projects/components/subcomponents/SkillTable.vue
  fe/src/models/ProjectSkillsColumns.ts
  fe/src/router/index.ts
  fe/src/stores/useCoachStore.ts
  fe/src/stores/useProjectStore.ts
  fe/src/stores/useSkillStore.ts
Labels: frontend

#349 register fix - experimental
  be/docker/Dockerfile
  be/docker/Dockerfile.production
  be/osoc/common/serializers.py
  be/osoc/common/signals.py
  be/osoc/common/views.py
  be/osoc/urls.py
Labels: backend

#362 backend tests fix
  be/osoc/common/models.py
  be/osoc/common/signals.py
  be/osoc/common/tests/__init__.py
  be/osoc/common/tests/test_models.py
Labels: bug, backend, tests

#352 Server deployment
  be/docker/docker-compose.yaml
Labels: bug, backend, production server

#355 Delete student
  fe/src/features/mails/MailList.vue
  fe/src/features/students/StudentPage.vue
  fe/src/features/students/components/DeleteStudentDialog.vue
  fe/src/stores/useStudentStore.ts
Labels: enhancement, frontend

#363 Be/tests
  be/osoc/common/tally/test_data.json
  be/osoc/common/tests/integration_tests.py
  be/osoc/common/tests/test_tallyform.py
  be/osoc/urls.py
Labels: backend, tests

#367 add pagination to get-conflicting-projects endpoint
  be/osoc/common/tests/integration_tests.py
  be/osoc/common/views.py
Labels: enhancement, backend

#326 Fe/mails pagination
  fe/src/components/SideBar.vue
  fe/src/features/mails/MailList.vue
  fe/src/features/users/AddUser.vue
  fe/src/features/users/UserList.vue
  fe/src/models/MailStudentColumns.ts
  fe/src/stores/useCoachStore.ts
  fe/src/stores/useMailStore.ts
  fe/src/stores/useStudentStore.ts
Labels: enhancement, frontend

#356 Fe/decision student
  be/osoc/common/views.py
  fe/src/features/students/StudentPage.vue
  fe/src/features/students/components/DecisionCard.vue
  fe/src/stores/useStudentStore.ts
Labels: enhancement, frontend

#379 added bulk status api endpoint
  be/osoc/common/serializers.py
  be/osoc/common/tests/integration_tests.py
  be/osoc/common/views.py
Labels: enhancement, backend

#378 added type to emails
  be/osoc/common/migrations/0002_sentemail_type.py
  be/osoc/common/migrations/0003_alter_sentemail_type.py
  be/osoc/common/models.py
  be/osoc/common/serializers.py
Labels: enhancement, backend

#365 Project Filters, Pagination & UI Improvements
  fe/src/App.vue
  fe/src/components/AppPage.vue
  fe/src/components/SideBar.vue
  fe/src/components/StudentCard.vue
  fe/src/components/TopToolbar.vue
  fe/src/features/mails/components/MailsOverview.vue
  fe/src/features/projects/ProjectList.vue
  fe/src/features/projects/components/ProjectCard.vue
  fe/src/features/students/SelectStudentsPage.vue
  fe/src/features/students/StudentPage.vue
  fe/src/features/students/components/AcademiaCard.vue
  fe/src/features/students/components/LanguageCard.vue
  fe/src/features/students/components/SkillsCard.vue
  fe/src/features/students/components/SuggestionsCard.vue
  fe/src/features/users/UserList.vue
  fe/src/quasar-variables.sass
  fe/src/stores/useProjectStore.ts
Labels: enhancement, frontend

#384 Fe/state sidebar
  fe/package-lock.json
  fe/package.json
  fe/src/components/SideBar.vue
  fe/src/features/mails/Status.ts
  fe/src/features/students/StudentPage.vue
  fe/src/stores/useStudentStore.ts
Labels: enhancement, frontend

#387 fix
  fe/package.json
Labels: bug, frontend, production server

#386 disable keepalive for editproject
  fe/src/components/AppPage.vue
  fe/src/features/projects/EditProject.vue
Labels: bug, frontend

#385 Be/delete all
  be/osoc/common/tests/integration_tests.py
  be/osoc/common/views.py
Labels: enhancement, backend

#381 Be/filter fix: filter on multiple statuses
  be/osoc/common/filters.py
  be/osoc/common/views.py
Labels: enhancement, backend

#364 Server CSRF issues.
  be/osoc/settings/prod.py
Labels: bug, production server

#382 Fe/bulk mails
  fe/src/components/DeleteDialog.vue
  fe/src/components/SideBar.vue
  fe/src/features/mails/MailList.vue
  fe/src/features/mails/Status.ts
  fe/src/features/projects/components/subcomponents/CoachTable.vue
  fe/src/features/students/StudentPage.vue
  fe/src/features/users/UserList.vue
  fe/src/models/MailsColumns.ts
  fe/src/models/Student.ts
  fe/src/models/UserColumns.ts
  fe/src/stores/useCoachStore.ts
  fe/src/stores/useMailStore.ts
  fe/src/stores/useStudentStore.ts
Labels: bug, enhancement, frontend

#403 fix project skill update bug
  be/osoc/common/serializers.py
Labels: backend

#406 Dependency rollback
  fe/package.json
Labels: bug, production server

#407 Sidebar improvements
  fe/package-lock.json
  fe/src/components/SideBar.vue
  fe/src/features/projects/ProjectList.vue
  fe/src/features/projects/components/ProjectCard.vue
  fe/src/stores/useProjectStore.ts
Labels: enhancement, frontend

#416 Enable secure websockets in production.
  be/docker/Dockerfile.production
  be/osoc/asgi.py
Labels: enhancement, production server

#410 Removed GH Signin + reset password at login page
  fe/src/components/OsocButton.vue
  fe/src/features/authentication/LoginForm.vue
Labels: enhancement, frontend

#409 Improved select student placeholder + 404 page
  fe/package-lock.json
  fe/package.json
  fe/src/components/NotFoundPage.vue
  fe/src/features/students/SelectStudentsPage.vue
  fe/src/main.ts
Labels: enhancement, frontend

#417 Hotfix
  .github/workflows/vue.yml
  fe/src/components/NotFoundPage.vue
  fe/tests/components/notFoundPage.test.ts
Labels: bug, production server

#415 Fe/mails changes
  fe/src/features/mails/MailList.vue
  fe/src/features/mails/components/MailsOverview.vue
  fe/src/models/ApprovalStates.ts
  fe/src/models/Mail.ts
  fe/src/models/MailsColumns.ts
  fe/src/stores/useMailStore.ts
Labels: enhancement, frontend

#413 add student count endpoint
  be/osoc/common/views.py
Labels: enhancement, backend

#414 project skill fix
  be/osoc/common/serializers.py
Labels: enhancement, backend

#392 added projects to coach serializer
  be/osoc/common/serializers.py
Labels: enhancement, backend

#418 Select Student bugfixes
  fe/src/components/SideBar.vue
  fe/src/features/students/StudentPage.vue
  fe/src/router/index.ts
Labels: bug, frontend

#408 SegmentedControl improvements
  fe/src/components/SegmentedControl.vue
  fe/src/components/SideBar.vue
  fe/src/components/StudentCard.vue
  fe/src/components/TopToolbar.vue
  fe/src/models/YesMaybeNoOptions.ts
  fe/src/stores/useStudentStore.ts
Labels: enhancement, frontend

#439 Fe/coach projects
  fe/src/features/mails/MailList.vue
  fe/src/features/users/UserList.vue
  fe/src/models/User.ts
  fe/src/stores/useProjectStore.ts
Labels: enhancement, frontend

#446 made extra_info field of project not required
  be/osoc/common/migrations/0004_alter_project_extra_info.py
  be/osoc/common/models.py
Labels: enhancement, backend

#452 added student conflict filter
  be/osoc/common/filters.py
  be/osoc/common/views.py
Labels: enhancement, backend

#427 Dark mode
  fe/src/App.vue
  fe/src/components/AppPage.vue
  fe/src/components/OsocButton.vue
  fe/src/components/SegmentedControl.vue
  fe/src/components/SideBar.vue
  fe/src/components/StudentCard.vue
  fe/src/components/TopToolbar.vue
  fe/src/features/mails/MailList.vue
  fe/src/features/mails/components/MailsOverview.vue
  fe/src/features/projects/CreateProject.vue
  fe/src/features/projects/ProjectList.vue
  fe/src/features/projects/components/ProjectCard.vue
  fe/src/features/projects/components/ProjectRoleChip.vue
  fe/src/features/projects/components/ProjectSkills.vue
  fe/src/features/projects/components/createprojectchip.vue
  fe/src/features/users/UserList.vue
  fe/src/main.ts
  fe/src/quasar-variables.sass
  fe/src/stores/useAuthenticationStore.ts
  fe/vite.config.ts
Labels: enhancement, frontend, nice to have

#319 changed some fields on_delete to SET_NULL
  be/osoc/common/migrations/0001_initial.py
  be/osoc/common/models.py
  be/osoc/common/serializers.py
  fe/src/components/StudentCard.vue
  fe/src/features/projects/components/ProjectCard.vue
  fe/src/features/students/StudentPage.vue
  fe/src/features/students/components/SuggestionsCard.vue
  fe/src/features/users/UserList.vue
  fe/src/models/User.ts
  fe/src/stores/useCoachStore.ts
Labels: backend

#456 Restrict coachview additions
  fe/src/components/SideBar.vue
  fe/src/features/authentication/LoginForm.vue
  fe/src/features/mails/MailList.vue
  fe/src/features/projects/CreateProject.vue
  fe/src/features/projects/components/MarkdownViewer.vue
  fe/src/features/projects/components/ProjectCard.vue
  fe/src/features/projects/components/createprojectchip.vue
  fe/src/features/students/StudentPage.vue
  fe/src/features/users/AddUser.vue
  fe/src/features/users/UserList.vue
  fe/src/stores/useAuthenticationStore.ts
  fe/src/stores/useProjectStore.ts
Labels: bug, frontend

#455 Delete Project
  fe/src/features/mails/MailList.vue
  fe/src/features/projects/CreateProject.vue
  fe/src/features/projects/components/ProjectCoaches.vue
  fe/src/features/projects/components/ProjectSkills.vue
  fe/src/features/projects/components/subcomponents/DeleteProjectDialog.vue
  fe/src/stores/useProjectStore.ts
Labels: enhancement, frontend

#453 Fe/project card small fixes
  fe/src/features/projects/components/CreateProjectChip.vue
  fe/src/features/projects/components/MarkdownViewer.vue
  fe/src/features/projects/components/ProjectCard.vue
  fe/src/features/projects/components/ProjectCoaches.vue
  fe/src/features/projects/components/ProjectSkills.vue
Labels: bug, frontend

#391 add csv-export
  be/osoc/common/serializers.py
  be/osoc/common/utils.py
  be/osoc/common/views.py
  be/osoc/urls.py
Labels: enhancement, backend

#441 add final decision to suggestions
  fe/src/components/SideBar.vue
  fe/src/features/mails/MailList.vue
  fe/src/features/students/StudentPage.vue
  fe/src/features/students/components/SuggestionRow.vue
  fe/src/features/students/components/SuggestionsCard.vue
  fe/src/features/users/UserList.vue
  fe/src/stores/useStudentStore.ts
Labels: enhancement, frontend

#459 Refresh Tokens
  fe/src/utils/axios.ts
Labels: bug, frontend

#460 coach filters
  fe/src/components/SegmentedControl.vue
  fe/src/components/TopToolbar.vue
  fe/src/features/projects/CreateProject.vue
  fe/src/features/projects/ProjectList.vue
  fe/src/features/projects/components/ProjectCoaches.vue
  fe/src/features/users/UserList.vue
  fe/src/stores/useCoachStore.ts
Labels: enhancement, frontend

#464 add filter support for csv-export endpoints
  be/osoc/common/views.py
Labels: backend

#454 backend tests
  be/osoc/common/permissions.py
  be/osoc/common/tests/integration_tests.py
  be/osoc/common/tests/test_auth.py
  be/osoc/common/tests/test_coaches.py
  be/osoc/common/tests/test_emails.py
  be/osoc/common/tests/test_filters.py
  be/osoc/common/tests/test_models.py
  be/osoc/common/tests/test_projects.py
  be/osoc/common/tests/test_skills.py
  be/osoc/common/tests/test_students.py
  be/osoc/common/tests/test_tallyform.py
  be/osoc/common/tests/test_utils.py
  be/osoc/common/views.py
Labels: backend, tests

#467 fix status
  fe/src/components/SideBar.vue
  fe/src/stores/useStudentStore.ts
Labels: bug, frontend

#469 Refresh Fix #3
  fe/src/stores/useAuthenticationStore.ts
  fe/src/utils/axios.ts
Labels: bug, frontend

#476 Small fixes
  fe/src/components/TopToolbar.vue
  fe/src/stores/useAuthenticationStore.ts
Labels: bug, frontend

#477 Dark mode fixes
  fe/src/App.vue
  fe/src/features/projects/ProjectList.vue
Labels: bug, frontend

#478 fixes
  fe/src/features/mails/MailList.vue
  fe/src/features/projects/CreateProject.vue
  fe/src/features/projects/components/ProjectSkills.vue
  fe/src/stores/useProjectStore.ts
  fe/src/stores/useSkillStore.ts
  fe/src/utils/axios.ts
Labels: bug, frontend

#450 Create user feedback
  fe/src/features/users/AddUser.vue
  fe/src/features/users/UserList.vue
Labels: enhancement, frontend

#479 Fixed warnings
  fe/src/components/AppPage.vue
  fe/src/components/OsocButton.vue
  fe/src/components/OsocTab.vue
  fe/src/components/SegmentedControl.vue
  fe/src/components/SideBar.vue
  fe/src/components/TopToolbar.vue
  fe/src/features/authentication/FormPage.vue
  fe/src/features/authentication/LoginForm.vue
  fe/src/features/authentication/components/GitHubSignInButton.vue
  fe/src/features/authentication/components/LightDarkButton.vue
  fe/src/features/mails/MailList.vue
  fe/src/features/projects/CreateProject.vue
  fe/src/features/projects/ProjectList.vue
  fe/src/features/projects/ResolveConflicts.vue
  fe/src/features/projects/components/BasicInfo.vue
  fe/src/features/projects/components/CreateProjectChip.vue
  fe/src/features/projects/components/MarkdownViewer.vue
  fe/src/features/projects/components/ProjectCard.vue
  fe/src/features/projects/components/ProjectCardSuggestion.vue
  fe/src/features/projects/components/ProjectCoaches.vue
  fe/src/features/projects/components/ProjectConflictCard.vue
  fe/src/features/projects/components/ProjectRoleChip.vue
  fe/src/features/projects/components/ProjectSkills.vue
  fe/src/features/projects/components/subcomponents/DeleteSkillDialog.vue
  fe/src/features/projects/components/subcomponents/NewSkillDialog.vue
  fe/src/features/students/StudentPage.vue
  fe/src/features/students/components/InfoDiv.vue
  fe/src/features/students/components/SuggestionRow.vue
  fe/src/features/students/components/SuggestionsCard.vue
  fe/src/models/Suggestion.ts
  fe/src/stores/useStudentStore.ts
Labels: bug, frontend

#481 fixed bug with switching between edit and new skill
  fe/src/features/projects/components/ProjectSkills.vue
Labels: bug, frontend

#482 Fix for sidebar filters
  fe/src/components/SideBar.vue
Labels: bug, frontend

#480 fix for manage users + deleted user comment
  fe/src/features/projects/components/ProjectCardSuggestion.vue
  fe/src/models/ProjectSuggestion.ts
  fe/src/stores/useCoachStore.ts
  fe/src/stores/useProjectConflictStore.ts
  fe/src/stores/useProjectStore.ts
Labels: bug, frontend

#483 Fix for student layout
  fe/src/components/DecisionIcon.vue
  fe/src/components/StudentCard.vue
  fe/src/features/students/StudentPage.vue
  fe/src/features/students/components/SuggestionRow.vue
Labels: bug, frontend

#451 Delete all
  be/osoc/common/tests/test_coaches.py
  be/osoc/common/tests/test_emails.py
  be/osoc/common/tests/test_projects.py
  be/osoc/common/tests/test_skills.py
  be/osoc/common/tests/test_students.py
  be/osoc/common/utils.py
  be/osoc/common/views.py
  fe/src/components/AdvancedPage.vue
  fe/src/components/ChangePasswordDialog.vue
  fe/src/components/TopToolbar.vue
  fe/src/features/mails/MailList.vue
  fe/src/router/index.ts
  fe/src/stores/useCoachStore.ts
  fe/src/stores/useMailStore.ts
  fe/src/stores/useProjectStore.ts
  fe/src/stores/useSkillStore.ts
  fe/src/stores/useStudentStore.ts
Labels: frontend

#485 Fe/last fixes
  fe/src/features/projects/ResolveConflicts.vue
  fe/src/features/projects/components/ProjectCard.vue
Labels: bug, frontend

#305 Front End Tests
  README.md
  fe/package.json
  fe/src/models/Project.ts
  fe/src/stores/useAuthenticationStore.ts
  fe/src/stores/useCoachStore.ts
  fe/src/stores/useProjectConflictStore.ts
  fe/src/stores/useProjectStore.ts
  fe/src/stores/useSkillStore.ts
  fe/src/stores/useStudentStore.ts
  fe/tests/components/gitHubSignInButton.disabledtest.ts
  fe/tests/mockUrlMappings.ts
  fe/tests/stores/authenticationStore.test.ts
  fe/tests/stores/coachStore.test.ts
  fe/tests/stores/mailStore.test.ts
  fe/tests/stores/projectConflictStore.test.ts
  fe/tests/stores/projectStore.test.ts
  fe/tests/stores/skillStore.test.ts
  fe/tests/stores/studentStore.test.ts
  fe/vitest.config.ts
Labels: help wanted, frontend, tests
